### ISSUE TITLE
Trouble using this with full paths

### ISSUE THREAD

**Issue by jgstew** [strawgate/make-prefetch#6]
This didn't work: 

`& ./C:\whatever\make-prefetch-master\get-prefetch.ps1 '.
\Firefox Setup 60.0.2esr.exe'`

This didn't work: 

`& ./get-prefetch.ps1 "C:\whatever\Downloads\Firefox Setup 60.0.2esr.exe"`

But this did work:

`& .\get-prefetch.ps1 '.\Firefox Setup 60.0.2esr.exe'`

I had to move the ps1 into the same folder as the file I wanted to get a prefetch for.

**Comment by strawgate** [comment]
This issue has been resolved with the latest push
